pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        // Provide Android Gradle plugin version for subprojects
        id 'com.android.application' version '8.1.0'
        id 'com.android.library' version '8.1.0'
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = 'email-reg-ms'
include ':android-client'