# Profile-specific properties for MySQL deployments
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# You can activate this with --spring.profiles.active=mysql or set env SPRING_PROFILES_ACTIVE=mysql
